[project]
name = "tgtg-whatsapp-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "python-crfsuite==0.9.8",
    "rasa>=3.6.21",
    "tgtg>=0.18.4",
]
